In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import joblib
import os##
from collections import Counter###
import random
#####
import vina
from vina import Vina

### u might want to consider to set a fixed random state wether u work with vina.exe or vina from python

### the logs are auto-printed during the docking process u can just copy and paste the cell output to a textfile(ex:log.text)

In [8]:
# to check python version u are on(windows vs wls)
!which python #for vina:i use python via wsl not the windows version
!python --version #check python versions
!conda list vina #to ensure vina library package is installed

/home/asser_ahmed/miniconda3/bin/python
Python 3.12.2
# packages in environment at /home/asser_ahmed/miniconda3:
#
# Name                    Version                   Build  Channel
vina                      1.2.6           py312h2ec8cdc_0    conda-forge


In [2]:
v=Vina(seed=42)
help(v)

Help on Vina in module vina.vina object:

class Vina(builtins.object)
 |  Vina(sf_name='vina', cpu=0, seed=0, no_refine=False, verbosity=1)
 |
 |  Methods defined here:
 |
 |  __init__(self, sf_name='vina', cpu=0, seed=0, no_refine=False, verbosity=1)
 |      Initialize a Vina object.
 |
 |      Args:
 |          sf_name (str): Scoring function name to use (Vina or ad4) (default: vina)
 |          cpu (int): Number of CPU to use (default: 0; use all of them)
 |          seed (int): Random seed (default: 0; ramdomly choosed)
 |          no_refine (boolean): when receptor is provided, do not use explicit receptor atoms
 |              (instead of precalculated grids) for: (1) local optimization and scoring after docking,
 |              (2) --local_only jobs, and (3) --score_only jobs (default: False)
 |          verbosity (int): verbosity 0: not output, 1: normal, 2: verbose (default: 1; some output)
 |
 |  __str__(self)
 |      Print basic information about Docking configuration (rigid

In [84]:
##
v=Vina(seed=42)
v.set_receptor(r"cox2(receptor).pdbqt")
v.set_ligand_from_file(r"ibuprofen(ligand).pdbqt")
v.compute_vina_maps(center=[9,-11,23],box_size=[16,30,19])
v.dock(exhaustiveness=8)
# v.write_poses("vina by python outputs/results_poses12.pdbqt", n_poses=9)


mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1      -6.6083     0.0000     0.0000
   2      -6.5509     4.4737     7.1497
   3      -6.4603     2.5205     3.1736
   4      -6.4191     2.3748     3.8806
   5      -6.3544     4.3145     6.3324
   6      -6.3533     1.7074     2.9052
   7      -6.2672     4.7007     7.2258
   8      -6.2629     4.5437     7.4487
   9      -6.2058     1.9681     2.2984
  10      -6.1926     2.4870     3.2022
  11      -6.1917     3.1582     4.4476
  12      -6.1028     4.5722     7.0486
  13      -6.0676     2.6889     5.9874
  14      -6.0223     2.3527     2.9843
  15      -5.9705     4.0975     7.0150
  16      -5.9256     2.1388     3.4241
  17      -5.8890     3.5071     6.1488
  18      -5.8636     3.1180     5.0429
  19      -5.8576     2.7921     3.9956
  20      -5.8001     1.7732     2.2936
done.ting Vina grid ... 
Performing docking (random seed: 42) ... 
0%   10   

In [7]:
##
v=Vina(seed=42,verbosity=2) #verbosity=2 ,gives extra info.,..there seems to be a printing shift issue with the printed logs
v.set_receptor(r"cox2(receptor).pdbqt")
v.set_ligand_from_file(r"ibuprofen(ligand).pdbqt")
v.compute_vina_maps(center=[9,-11,23],box_size=[16,30,19])
v.dock(exhaustiveness=8)
# v.write_poses("vina by python outputs/results_poses12.pdbqt", n_poses=9)

.0000     0.0000
   2      -6.5509     4.4737     7.1497
   3      -6.4603     2.5205     3.1736
   4      -6.4191     2.3748     3.8806
   5      -6.3544     4.3145     6.3324
   6      -6.3533     1.7074     2.9052
   7      -6.2672     4.7007     7.2258
   8      -6.2629     4.5437     7.4487
   9      -6.2058     1.9681     2.2984
  10      -6.1926     2.4870     3.2022
  11      -6.1917     3.1582     4.4476
  12      -6.1028     4.5722     7.0486
  13      -6.0676     2.6889     5.9874
  14      -6.0223     2.3527     2.9843
  15      -5.9705     4.0975     7.0150
  16      -5.9256     2.1388     3.4241
  17      -5.8890     3.5071     6.1488
  18      -5.8636     3.1180     5.0429
  19      -5.8576     2.7921     3.9956
  20      -5.8001     1.7732     2.2936
Computing Vina grid ... done.
Performing docking (random seed: 42) ... 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
********************************************

### the modification/rotations/..,poses ,models,..... is for the ligand not the receptor(fixed)

---
---

### save as log.txt
```plain text
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -6.608          0          0
   2       -6.551      4.474       7.15
   3        -6.46      2.521      3.174
   4       -6.419      2.375      3.881
   5       -6.354      4.315      6.332
   6       -6.353      1.707      2.905
   7       -6.267      4.701      7.226
   8       -6.263      4.544      7.449
   9       -6.206      1.968      2.298
  10       -6.193      2.487      3.202
  11       -6.192      3.158      4.448
  12       -6.103      4.572      7.049
  13       -6.068      2.689      5.987
  14       -6.022      2.353      2.984
  15       -5.971      4.097      7.015
  16       -5.926      2.139      3.424
  17       -5.889      3.507      6.149
  18       -5.864      3.118      5.043
  19       -5.858      2.792      3.996
  20         -5.8      1.773      2.294
Computing Vina grid ... done.
Performing docking (random seed: 40) ... 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
```

In [85]:
v.__str__()

'Receptor (rigid): cox2(receptor).pdbqt\nReceptor (flex): None\nLigands: ibuprofen(ligand).pdbqt\nScoring function: vina\nWeights: -0.035579 -0.005156 0.840245 -0.035069 -0.587439 50.000000 0.058460\nNo refinement with receptor atoms: False\nBox center: 9.000 -11.000 23.000\nBox dimensions: 16.00 30.00 19.00\nBox spacing: 0.375\nBox even NELEMENTS: True\nSeed: 42'

In [86]:
v.info()

{'rigid_receptor': 'cox2(receptor).pdbqt',
 'flex_receptor': None,
 'ligands': ['ibuprofen(ligand).pdbqt'],
 'scoring_function': 'vina',
 'weights': (-0.035579,
  -0.005156,
  0.840245,
  -0.035069,
  -0.587439,
  50,
  0.05846),
 'no_refine': False,
 'box_center': [9, -11, 23],
 'box_size': [16, 30, 19],
 'box_spacing': 0.375,
 'box_even_elements': True,
 'seed': 42}

In [87]:
models=v.poses()
print (models)

MODEL 1
REMARK VINA RESULT:    -6.608      0.000      0.000
REMARK INTER + INTRA:          -8.765
REMARK INTER:                  -8.347
REMARK INTRA:                  -0.419
REMARK UNBOUND:                -0.419
REMARK  5 active torsions:
REMARK  status: ('A' for Active; 'I' for Inactive)
REMARK    1  A    between atoms: O_1  and  C_15 
REMARK    2  A    between atoms: C_3  and  C_4 
REMARK    3  A    between atoms: C_4  and  C_5 
REMARK    4  A    between atoms: C_6  and  C_7 
REMARK    5  A    between atoms: C_7  and  C_15 
ROOT
HETATM    1  O   UNL     1       4.705 -15.526  21.272  1.00  0.00    -0.776 OA
HETATM    2  H   UNL     1       4.739 -15.794  22.215  1.00  0.00     0.167 HD
ENDROOT
BRANCH   1   3
HETATM    3  C   UNL     1       6.007 -15.383  20.936  1.00  0.00     0.148 C 
HETATM    4  O   UNL     1       6.740 -16.359  20.944  1.00  0.00    -0.649 OA
BRANCH   3   5
HETATM    5  C   UNL     1       6.339 -13.958  20.525  1.00  0.00     0.112 C 
HETATM    6  C   UNL     

In [88]:
energies = v.energies(n_poses=20, energy_range=3.0)
print(energies)  # Check format

[[-6.608 -8.347 -0.419  1.738 -0.419]
 [-6.551 -8.253 -0.44   1.723 -0.419]
 [-6.46  -8.228 -0.35   1.699 -0.419]
 [-6.419 -8.193 -0.333  1.689 -0.419]
 [-6.354 -8.022 -0.423  1.672 -0.419]
 [-6.353 -8.095 -0.348  1.671 -0.419]
 [-6.267 -7.83  -0.504  1.649 -0.419]
 [-6.263 -7.826 -0.503  1.648 -0.419]
 [-6.206 -7.709 -0.548  1.633 -0.419]
 [-6.193 -7.739 -0.501  1.629 -0.419]
 [-6.192 -7.733 -0.507  1.629 -0.419]
 [-6.103 -7.605 -0.522  1.605 -0.419]
 [-6.068 -7.569 -0.513  1.596 -0.419]
 [-6.022 -7.567 -0.458  1.584 -0.419]
 [-5.971 -7.427 -0.532  1.571 -0.419]
 [-5.926 -7.475 -0.428  1.559 -0.419]
 [-5.889 -7.419 -0.438  1.549 -0.419]
 [-5.864 -7.307 -0.517  1.543 -0.419]
 [-5.858 -7.371 -0.446  1.541 -0.419]
 [-5.8   -7.264 -0.481  1.526 -0.419]]


### if u have a saved ligand model(.pdbqt) and u just want to see the binding enrgy/affinity of a fixed pose without redocking:
### use .score() instead of .dock()

In [ ]:
# # for vina to accept the ligand model u must remove the model1,end mdl in the txt of the .pdbqt file so, it recognises it as a single model
# # (not in multi-model format)
# file_path=r"vina by python outputs/results_poses7_bestmodel.pdbqt"
# v.set_receptor(r"cox2(receptor).pdbqt")
# v.set_ligand_from_file(file_path) # the docking modifies the ligand not the receptor!
# v.compute_vina_maps(center=[9,-11,23],box_size=[16,30,19])
# v.score()#Calculates binding energy of a fixed pose (without moving it).

In [89]:
# for vina to accept the ligand model u must remove the model1,end mdl in the txt of the .pdbqt file so, it recognises it as a single model
# (not in multi-model format)
file_path=r"vina by python outputs/results_poses7_bestmodel.pdbqt"
v.set_receptor(r"cox2(receptor).pdbqt")
v.set_ligand_from_file(file_path) # the docking modifies the ligand not the receptor!
v.compute_vina_maps(center=[9,-11,23],box_size=[16,30,19])
v.score()#Calculates binding energy of a fixed pose (without moving it).


mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1      -6.6083     0.0000     0.0000
   2      -6.5509     4.4737     7.1497
   3      -6.4603     2.5205     3.1736
   4      -6.4191     2.3748     3.8806
   5      -6.3544     4.3145     6.3324
   6      -6.3533     1.7074     2.9052
   7      -6.2672     4.7007     7.2258
   8      -6.2629     4.5437     7.4487
   9      -6.2058     1.9681     2.2984
  10      -6.1926     2.4870     3.2022
  11      -6.1917     3.1582     4.4476
  12      -6.1028     4.5722     7.0486
  13      -6.0676     2.6889     5.9874
  14      -6.0223     2.3527     2.9843
  15      -5.9705     4.0975     7.0150
  16      -5.9256     2.1388     3.4241
  17      -5.8890     3.5071     6.1488
  18      -5.8636     3.1180     5.0429
  19      -5.8576     2.7921     3.9956
  20      -5.8001     1.7732     2.2936
Computing Vina grid ... 

array([-6.608, -8.346,  0.   ,  0.   ,  0.   , -0.417,  1.738, -0.417])

done.


### **re-running the cell with v.score() multiple times might cause it to stop from auto-printing the logs**
### **if this happens restart the kernel or close and open the notebook(without shutting the kernel) or try both.**